spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dockerinit
    redis:
      host: localhost
      port: 6379
      timeout: 1000ms

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.redis.connection.lettuce: INFO