spring:
  application:
    name: dockerinit
  data:
    mongodb:
      uri: ${MONGODB_URI}
#      username: ${MONGODB_USERNAME:}
#      password: ${MONGODB_PASSWORD:}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
#      password: ${REDIS_PASSWORD:}
      timeout: 1000ms

# 로그 레벨 참고
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.redis.connection.lettuce: INFO
