spring:
  application:
    name: dockerinit
  cache:
    type: redis
    cache-names:
      - 'composePreset:detail'
      - 'composePreset:list'
      - 'preset:list'
      - 'preset:detail'
      - 'preset:artifacts'
    redis:
      time-to-live: 600000
      use-key-prefix: true
      key-prefix: 'di:cache:'
      cache-null-values: false